# Generated by Django 5.0.4 on 2024-05-01 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_de_notif', models.CharField(max_length=15)),
                ('titre', models.CharField(max_length=15)),
                ('contenue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('numtel', models.IntegerField()),
                ('groupSanguin', models.CharField(max_length=2)),
                ('willaya', models.CharField(max_length=20)),
                ('daira', models.CharField(max_length=20)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='possede_compte', to='globalApp.compte')),
            ],
        ),
        migrations.CreateModel(
            name='NotifEnvoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalApp.notification')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Donneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statu', models.CharField(max_length=8)),
                ('date_dernier_don', models.DateField(null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='est_utilisateur', to='globalApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, null=True)),
                ('groupSanguin', models.CharField(max_length=2)),
                ('date_de_publication', models.DateTimeField(auto_now_add=True)),
                ('date_de_modification', models.DateTimeField(auto_now=True, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cree_annonce', to='globalApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='EffectueDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_don', models.DateField()),
                ('type_de_don', models.CharField(max_length=15)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectue', to='globalApp.donneur')),
            ],
            options={
                'unique_together': {('donneur', 'date_de_don')},
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_demande', models.DateTimeField(auto_now_add=True)),
                ('type_demande', models.CharField(max_length=15)),
                ('etat_demande', models.CharField(max_length=15)),
                ('donneur_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalApp.donneur')),
                ('utilisateur_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalApp.utilisateur')),
            ],
            options={
                'unique_together': {('donneur_dest', 'utilisateur_src')},
            },
        ),
    ]
