# Generated by Django 5.0.4 on 2024-05-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='compte',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Compte',
        ),
    ]
