# Generated by Django 5.0.4 on 2024-05-02 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalApp', '0002_remove_utilisateur_compte_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=100)),
                ('utilisateur_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('utilisateur_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalApp.utilisateur')),
            ],
        ),
    ]
