# Generated by Django 5.0.4 on 2024-05-02 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalApp', '0003_problems_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cree_annonce', to='globalApp.utilisateur'),
        ),
    ]
