# Generated by Django 5.0.4 on 2024-05-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalApp', '0004_alter_annonce_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='place',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
