# Generated by Django 5.0.4 on 2024-05-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalApp', '0005_annonce_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='date_de_Don_max',
            field=models.DateTimeField(null=True),
        ),
    ]
